# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
version: 1
policy:
  pullRequests: public
tasks:
  - $if: 'tasks_for == "github-pull-request" && event["action"] in ["opened", "reopened", "synchronize"]'
    then:
      created: {$fromNow: ''}
      deadline: {$fromNow: '2 hours'}
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      scopes: []
      payload:
        maxRunTime: 7200
        image: mozillamobile/android-components:1.5
        command:
          - /bin/bash
          - --login
          - -cx
          - >-
            cd ..
            && git clone ${event.pull_request.head.repo.clone_url}
            && cd reference-browser
            && git config advice.detachedHead false
            && git checkout ${event.pull_request.head.sha}
            && ./gradlew --no-daemon clean assemble ktlint detektCheck lint
        artifacts:
          public/reports:
            type: directory
            path: /build/reference-browser/app/build/reports
            expires: {$fromNow: '1 week'}
      metadata:
        name: Reference Browser - Pull request
        description: Building reference browser - triggered by a pull request.
        owner: ${event.pull_request.user.login}@users.noreply.github.com
        source: ${event.repository.url}
  - $if: 'tasks_for == "github-push"'
    then:
      $if: 'event.ref == "refs/heads/master"'
      then:
        created: {$fromNow: ''}
        deadline: {$fromNow: '2 hours'}
        provisionerId: aws-provisioner-v1
        workerType: github-worker
        scopes: []
        payload:
          maxRunTime: 7200
          image: mozillamobile/android-components:1.5
          command:
            - /bin/bash
            - --login
            - -cx
            - >-
              cd ..
              && git clone https://github.com/mozilla-mobile/reference-browser.git
              && cd reference-browser
              && git config advice.detachedHead false
              && git checkout ${event.after}
              && ./gradlew --no-daemon clean assemble ktlint detektCheck lint
          artifacts:
            public/reports:
              type: directory
              path: /build/reference-browser/app/build/reports
              expires: {$fromNow: '1 week'}
            public/builds:
              type: directory
              path: /build/reference-browser/app/build/outputs/apk
        metadata:
          name: Reference Browser - Master push
          description: Building reference browser - triggered by a pull request.
          owner: ${event.pull_request.user.login}@users.noreply.github.com
          source: ${event.repository.url}
