# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
version: 1
policy:
  pullRequests: public
tasks:
  - $if: 'tasks_for == "github-pull-request" && event["action"] in ["opened", "reopened", "synchronize"]'
    then:
      $let:
        decision_task_id: {$eval: as_slugid("decision_task")}
        expires_in: {$fromNow: '1 year'}
        scheduler_id: taskcluster-github
        user: ${event.sender.login}
        head_branch: ${event.pull_request.head.ref}
        head_rev: ${event.pull_request.head.sha}
        repository: ${event.pull_request.head.repo.clone_url}
        pull_request_title: ${event.pull_request.title}
        pull_request_number: ${event.pull_request.number}
        pull_request_url: ${event.pull_request.html_url}
      in:
        taskId: ${decision_task_id}
        taskGroupId: ${decision_task_id}
        created: {$fromNow: ''}
        expires: ${expires_in}
        deadline: {$fromNow: '2 hours'}
        provisionerId: aws-provisioner-v1
        workerType: github-worker
        scopes:
          - queue:create-task:aws-provisioner-v1/github-worker
          - queue:scheduler-id:${scheduler_id}
        payload:
          maxRunTime: 7200
          image: mozillamobile/android-components:1.10
          env:
            TASK_ID: ${decision_task_id}
            SCHEDULER_ID: ${scheduler_id}
            MOBILE_HEAD_REPOSITORY: ${repository}
            MOBILE_HEAD_BRANCH: ${head_branch}
            MOBILE_HEAD_REV: ${head_rev}
            GITHUB_PULL_TITLE: ${pull_request_title}
          command:
            - /bin/bash
            - --login
            - -cx
            - >-
              cd ..
              && git clone ${event.pull_request.head.repo.clone_url}
              && cd reference-browser
              && git config advice.detachedHead false
              && git checkout ${event.pull_request.head.sha}
              && python automation/taskcluster/decision_task.py
          features:
            taskclusterProxy: true
          artifacts:
            public/reports:
              type: directory
              path: /build/reference-browser/app/build/reports
              expires: {$fromNow: '1 week'}
        metadata:
          name: Decision task
          description: Building reference browser - triggered by a pull request.
          owner: ${event.pull_request.user.login}@users.noreply.github.com
          source: ${event.repository.url}
  - $if: 'tasks_for == "cron"'
    then:
      $let:
        decision_task_id: {$eval: as_slugid('decision_task')}
        expires_in: {$fromNow: '1 year'}
        repository: https://github.com/mozilla-mobile/reference-browser
        scheduler_id: taskcluster-github
      in:
        taskId: ${decision_task_id}
        taskGroupId: ${decision_task_id}   # Must be explicit because of Chain of Trust
        created: {$fromNow: ''}
        deadline: {$fromNow: '2 hours'}
        expires: ${expires_in}
        schedulerId: ${scheduler_id}   # Must be explicit because of Chain of Trust
        provisionerId: aws-provisioner-v1
        workerType: gecko-focus   # This workerType has ChainOfTrust enabled
        requires: all-completed   # Must be explicit because of Chain of Trust
        priority: medium
        retries: 5
        scopes:
          - queue:scheduler-id:${scheduler_id}
          - queue:create-task:highest:aws-provisioner-v1/gecko-focus
          - queue:create-task:highest:scriptworker-prov-v1/mobile-signing-v1
          - queue:create-task:highest:scriptworker-prov-v1/mobile-pushapk-v1
          - project:mobile:reference-browser:releng:signing:cert:release-signing
          - project:mobile:reference-browser:releng:signing:format:reference-browser-jar
          - project:mobile:reference-browser:releng:googleplay:product:reference-browser
          - secrets:get:project/reference-browser/tokens
          - queue:route:index.project.mobile.reference-browser.nightly.latest
        payload:
          maxRunTime: 600   # Decision should remain fast enough to schedule a handful of tasks
          image: mozillamobile/android-components:1.10
          features:
            taskclusterProxy: true
            chainOfTrust: true
          env:
            TASK_ID: ${decision_task_id}
            SCHEDULER_ID: ${scheduler_id}
            MOBILE_HEAD_REV: ${event.release.tag_name}
          command:
            - /bin/bash
            - --login
            - -cx
            - >-
              git fetch origin --tags
              && git config advice.detachedHead false
              && git reset --hard origin/master
              && python automation/taskcluster/decision_task_nightly.py \
                --commit \
                --output app/build/outputs/apk \
                --apk geckoNightlyX86/release/app-geckoNightly-x86-x86-release-unsigned.apk \
                --apk gechoNightlyArm/release/app-geckoNightly-arm-armeabi-v7a-release-unsigned.apk
          artifacts:
            public/task-graph.json:
              type: file
              path: /opt/reference-browser/task-graph.json
              expires: ${expires_in}
            public/actions.json:
              type: file
              path: /opt/reference-browser/actions.json
              expires: ${expires_in}
            public/parameters.yml:
              type: file
              path: /opt/reference-browser/parameters.yml
              expires: ${expires_in}
        extra:
          cron: {$json: {$eval: 'cron'}}
          tasks_for: ${tasks_for}
        metadata:
          name: Decision task (nightly)
          description: Scheduling tasks for nightly release of reference browser
          owner: skaspari@mozilla.com
          source: ${repository}/raw/${event.release.tag_name}/.taskcluster.yml
